protected/controllers/AdminController.php
<?php
if (!isset($_SESSION)) { session_start(); }

class AdminController extends CController
{
	
	public $layout='admin_layout';	
	public $body_class='';
	public $is_newupdate=false;
	
	public function init()
	{			
		 // set website timezone
		 $website_timezone=Yii::app()->functions->getOptionAdmin("website_timezone" );		 
		 if (!empty($website_timezone)){		 	
		 	Yii::app()->timeZone=$website_timezone;
		 }		 				 
		 
		 //Yii::app()->language="ph";		 
		 if(isset($_GET['lang'])){
		 	Yii::app()->language=$_GET['lang'];
		 }
	}
	
	public function beforeAction($action)
	{

		$action_name= $action->id ;
		$accept_controller=array('login','ajax','forgotpass');
		if(!AdminFunctions::islogin()){			
			if(!in_array($action_name,$accept_controller)){
				$this->redirect(Yii::app()->createUrl('/admin/login'));
			}
		}
		
		ScriptManagerAdmin::scripts();
		
		$cs = Yii::app()->getClientScript();
		$jslang=json_encode(AdminFunctions::jsLang());
		$cs->registerScript(
		  'jslang',
		 "var jslang=$jslang;",
		  CClientScript::POS_HEAD
		);
				
		$js_lang_validator=Yii::app()->functions->jsLanguageValidator();
		$js_lang=Yii::app()->functions->jsLanguageAdmin();
		$cs->registerScript(
		  'jsLanguageValidator',
		  'var jsLanguageValidator = '.json_encode($js_lang_validator).'
		  ',
		  CClientScript::POS_HEAD
		);				
		$cs->registerScript(
		  'js_lang',
		  'var js_lang = '.json_encode($js_lang).';
		  ',
		  CClientScript::POS_HEAD
		);
				
		$language=Yii::app()->language;
		$cs->registerScript(
		  'language',
		 "var language='$language';",
		  CClientScript::POS_HEAD
		);
		
		return true;
	}
	
	public function actionLogin()
	{
		if (AdminFunctions::islogin()){
			$this->redirect(Yii::app()->createUrl('/admin/dashboard'));
			Yii::app()->end();
		}
		$this->body_class="login";
		$this->render('login');
	}
	
	public function actionLogout()
	{
		unset($_SESSION['mobilogrd_admin']);
		$this->redirect(Yii::app()->createUrl('/admin/login'));
	}
	
	public function actionIndex()
	{
		$cs = Yii::app()->getClientScript(); 
		
		Yii::app()->clientScript->registerScriptFile(
		Yii::app()->baseUrl . '/assets/amcharts/amcharts.js'
        ,CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/serial.js',
        CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/themes/light.js',
        CClientScript::POS_END);		
        
        if(AdminFunctions::checkNewVersion()){
        	$this->is_newupdate=true;
        }
        
		$this->render('dashboard');
	}
	
	public function actionDashBoard()
	{
		$cs = Yii::app()->getClientScript(); 
		
		Yii::app()->clientScript->registerScriptFile(
		Yii::app()->baseUrl . '/assets/amcharts/amcharts.js'
        ,CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/serial.js',
        CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/themes/light.js',
        CClientScript::POS_END);		
		
        /*check for new update tables*/
        if(AdminFunctions::checkNewVersion()){
        	$this->is_newupdate=true;
        }
        
		$this->render('dashboard');		
	}
	
	public function actionPlanList()
	{
		$this->render('plan-list');
	}
	
	public function actioncustomerList()
	{
		$this->render('customer-list');
	}
	
	public function actionpaymentList()
	{
		$this->render('payment-settings',array(
		  'payment_list'=>AdminFunctions::paymentGatewayList()
		));
	}
	
	public function actionSms()
	{
		$this->render('sms-setttings');
	}
	
	public function actionSettings()
	{
		$logo=AdminFunctions::getImageLink('website_logo');
		$this->render('general-setttings',array(
		 'logo'=>$logo
		));
	}
	
	public function actionProfile()
	{
		$admin_id= AdminFunctions::getAdminID();
		if ( $res=AdminFunctions::getAdminDetailsByID($admin_id)){
			$this->render('profile',array(
			 'data'=>$res
			));
		} else $this->redirect(Yii::app()->createUrl('/admin/login'));
	}
	
	public function actionplanNew()
	{
		$data=array();
		if (isset($_GET['id'])){
			if($data=AdminFunctions::getRecordsFromTable("plan",'plan_id',$_GET['id'])){				
			} 
		}
		$this->render('plans',array(		 
		 'data'=>$data
		));
	}
	
	public function actioncustomerNew()
	{
		$data=array();
		if (isset($_GET['id'])){
			if($data=AdminFunctions::getRecordsFromTable("customer",'customer_id',$_GET['id'])){				
			} 
		}
		$this->render('customer-new',array(		 
		 'data'=>$data
		));
	}
	
	public function actionReports()
	{
		$this->render('reports');
	}
	
	public function actionTemplates()
	{
		$this->render('templates');
	}
	
	public function actionCurrency()
	{
		$this->render('currency');
	}
	
	public function actioncurrencyNew()
	{
		$res='';
		if ( isset($_GET['id'])){
			if (!$res=AdminFunctions::getRecordsFromTable("currency",'curr_id',$_GET['id'])){				
			    $this->redirect(Yii::app()->createUrl('/admin/currency'));
			} 
		}
		$this->render('currency-new',array(
		  'data'=>$res
		));
	}
	
	public function actionLanguage()
	{
		$lang_list=AdminFunctions::getLanguage();
		$selected_lang=getOptionA('language_list');
		$selected_lang=!empty($selected_lang)?json_decode($selected_lang):false;		
		$this->render('language',array(
		  'list'=>$lang_list,
		  'selected_lang'=>$selected_lang
		));
	}
	
	public function actionmobileSettings()
	{
		$this->render('mobile-settings',array(
		  'json'=>getOptionA('services_json')
		));
	}
	
	public function actionCustomPage()
	{
		$this->render('custom-page');
	}
	
	public function actionrptCustomer()
	{
		$this->render('rpt-customer');
	}
	
	public function actionrptSales()
	{
		$this->render('rpt-sales');
	}
	
	public function actionrptSms()
	{
		$this->render('rpt-sms');
	}
	
	public function actionrptEmail()
	{
		$this->render('rpt-email');
	}
	
	public function actionrptPush()
	{
		$this->render('rpt-push');
	}
	
	public function actionExport()
	{		
		require_once('export.php');
	}	
	
	public function actioncustompageNew()
	{
		Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/SCEditor/jquery.sceditor.bbcode.min.js',
		CClientScript::POS_END
		);			
				
		$baseUrl = Yii::app()->baseUrl.""; 
		$cs = Yii::app()->getClientScript();				
		$cs->registerCssFile($baseUrl."/assets/SCEditor/themes/default.min.css");		
		
		
		$this->render('custom-page-new',array(
		 'data'=>AdminFunctions::getCustomPage( isset($_GET['id'])?$_GET['id']:'' )
		));
	}
	
	public function actioncustompageAssign()
	{		
		$data=AdminFunctions::getCustomList("published");
		$this->render('custom-page-assign',array(
		 'data'=>$data	
		));
	}
			
	public function actionsetlang()
	{		
		if(!empty($_GET['action'])){
			$url=Yii::app()->createUrl("admin/".$_GET['action'],array(
			  'lang'=>$_GET['lang']
			));
		} else {
			$url=Yii::app()->createUrl("admin/dashboard",array(
			  'lang'=>$_GET['lang']
			));
		}
		/*dump($url);				
		die();*/
		$this->redirect($url);
	}
	
	public function actionPayments()
	{
		if(!isset($_GET['customer_id'])){
			$_GET['customer_id']='';
		}
		$res=AdminFunctions::getCustomerPaymentLogs($_GET['customer_id']);
		$customer_data=AdminFunctions::getCustomerByID($_GET['customer_id']);
		$this->render('payments',array(
		 'data'=>$res,
		 'customer_data'=>$customer_data
		));
	}
	
	public function actioncron()
	{
		$this->render('cron');
	}
	
	public function actionForgotPass()
	{		
		$token=isset($_GET['token'])?$_GET['token']:'';
		if ($res=AdminFunctions::getAdminByPassword($token)){
		   $this->body_class="login";
		   $this->render('change-password',array(
		     'token'=>$token
		   ));
		} else {
			$this->render('error',array(
			  'msg'=>t("Token is not valid")
			));
		}
	}
	
	public function actionServices()
	{
		$this->render('services-list',array(
		'data'=>AdminFunctions::servicesFullList(0)
		));
	}
	
	public function actionServicesNew()
	{
		$res='';
		if ( isset($_GET['id'])){
			if (!$res=AdminFunctions::getRecordsFromTable("services",'services_id',$_GET['id'])){				
			    $this->redirect(Yii::app()->createUrl('/admin/services'));
			} 
		}
		$this->render('services-new',array(
		  'data'=>$res
		));
	}
	
	public function actionSeo()
	{
		$this->render('seo');
	}
	
	public function actionPromocode()
	{
		$this->render('promo-code-list');
	}
	
	public function actionPromoCodeNew()
	{
		$data=AdminFunctions::getPromoCodeByID(isset($_GET['id'])?$_GET['id']:'');
		$this->render('promo-code-add',array(
		  'data'=>$data
		));
	}
	
	public function actionTestEmail()
	{
		$this->render('testemail');
	}
	
	public function actionmap_settings()
	{
		$country_list=require_once('CountryCode.php');
		$this->render('map_settings',array(
		  'country_list'=>$country_list
		));
	}
	
	public function actiontest_map_api()
	{
		
		$this->pageTitle = t("Test Map");
		
		$message = ''; $resp = array(); $lat = ''; $lng='';
		
		$map_provider = MapsWrapper::getMapProvider();
		$map_api = isset($map_provider['map_api'])?$map_provider['map_api']:'';
		$provider = isset($map_provider['provider'])?$map_provider['provider']:'';		
		
		try {					
			MapsWrapper::init($map_provider);
			$resp = MapsWrapper::geoCodeAdress("los angeles california");			
			$lat = $resp['lat']; $lng = $resp['long']; 
			MapsWrapper::saveLogs($provider,'geoCodeAdress',$resp);
		} catch (Exception $e) {
			$message = $e->getMessage();
			MapsWrapper::saveLogs($provider,'geoCodeAdress',$message);
		}					
		
		if($provider=="google"):
			Driver::registerJS(array(
			  '//maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key='.urlencode($map_api),
			  Yii::app()->baseUrl . '/assets/gmaps.js',
			  Yii::app()->baseUrl . '/assets/map_wrapper.js',
			));
		else :
		   Driver::registerJS(array(			  

protected/views/admin/custom-page.php
<div class="card">
 <div class="card-content">
   
  <div class="row">
    <div class="col s6">
      <h5><?php echo t("Custom page")?></h5>
    </div>
    <div class="col s6 right-align">
      <a title="<?php echo t("new page")?>" href="<?php echo Yii::app()->createUrl('/admin/custompage-new')?>" class="btn-floating btn-small waves-effect waves-light">
        <i class="material-icons">add</i>
      </a>
      
      <a title="<?php echo t("assign page")?>" href="<?php echo Yii::app()->createUrl('/admin/custompage-assign')?>" class="btn-floating btn-small waves-effect waves-light">
        <i class="material-icons">web</i>
      </a>
      
    </div>
  </div> <!--row-->
  
  
  <form id="frm_table" method="POST">
  <?php echo CHtml::hiddenField('action','customPageList');?>
   <table id="table_list" class="bordered highlight responsive-table">
    <thead>
      <tr>
       <th width="5%"><?php echo t("ID")?></th>
       <th width="10%"><?php echo t("Slug")?></th>
       <th width="10%"><?php echo t("Page title")?></th>
       <th width="10%"><?php echo t("Status")?></th>
       <th width="10%"><?php echo t("Date")?></th>
       <th width="10%"><?php echo t("lang")?></th>
       <th width="10%"><?php echo t("Actions")?></th>
      </tr>
    </thead>
    <tbody>     
    </tbody>
   </table> 
   </form>
  
  
 </div> <!--card-content-->
</div> <!--card-->

protected/views/admin/error.php
<div class="page-content sections">
<div class="container medium"> 

   <h2 class="text-center"><?php echo t("Oops something went wrong")?></h2>
   
   <?php if(!empty($msg)):?>
   <p class="text-danger top40 text-center"><?php echo $msg;?></p>
   <?php endif;?>
   
</div> <!--container-->   
</div> <!--sections-->

protected/views/admin/menu.php
<nav class="teal lighten-1">
<div class="nav-wrapper">
  <a href="<?php echo Yii::app()->createUrl('/admin/dashboard')?>" class="brand-logo">    
    <img src="<?php echo FrontFunctions::getLogoURL() ?>">
  </a>
  <ul id="nav-mobile" class="right hide-on-med-and-down">
  
    <li>
      <a href="<?php echo Yii::app()->createUrl('/front/index')?>" target="_blank">
      <i class="material-icons left">language</i> <?php echo t("View Site")?>
      </a>
    </li>
    
    <li>
    <a class="dropdown-button" href="#!" data-activates="reports-menu" style="width:150px;">
    <?php echo t("Reports")?>
    <i class="material-icons right">arrow_drop_down</i>
    </a>
    </li>
    
    <li>
      <a href="<?php echo Yii::app()->createUrl('/admin/profile')?>">
      <i class="material-icons left">perm_identity</i> <?php echo t("Hello")." ".AdminFunctions::getAdminUsername()?>
      </a>
    </li>    
    
    <li>
    <a class="dropdown-button" href="#!" data-activates="language-menu">
    <?php echo !empty($current_lang)?strtoupper($current_lang):'En'?>
    <i class="material-icons right">arrow_drop_down</i>
    </a>
    </li>
    
    <li>
     <a href="<?php echo Yii::app()->createUrl('/admin/logout')?>">
      <i class="material-icons">input</i>
     </a>
    </li>
  </ul>
</div>
</nav>

<ul id="reports-menu" class="dropdown-content">
  <li><a href="<?php echo Yii::app()->createUrl('admin/rpt-customer')?>"><?php echo t("Customer Signup")?></a></li>
  <li><a href="<?php echo Yii::app()->createUrl('admin/rpt-sales')?>"><?php echo t("Sales report")?></a></li>  
  <li><a href="<?php echo Yii::app()->createUrl('admin/rpt-sms')?>"><?php echo t("SMS Logs")?></a></li>
  <li><a href="<?php echo Yii::app()->createUrl('admin/rpt-email')?>"><?php echo t("Email Logs")?></a></li>
  <li><a href="<?php echo Yii::app()->createUrl('admin/rpt-push')?>"><?php echo t("Push Logs")?></a></li>  
  <li><a href="<?php echo Yii::app()->createUrl('admin/api_logs')?>"><?php echo t("Map Logs")?></a></li> 
</ul>

<?php 
if(!empty($language)){
	$language=json_decode($language,true);	
}
$action_name=Yii::app()->controller->action->id;
?> 
<ul id="language-menu" class="dropdown-content">  
<?php if(is_array($language) && count($language)>=1):?>
<?php foreach ($language as $val_lang) :?>
<li>
 <a href="<?php echo Yii::app()->getBaseUrl(true)."/admin/setlang/?lang=$val_lang&action=$action_name"?>">
 <?php echo $val_lang?>
 </a>
</li>
<?php endforeach;?>
<?php endif;?>
</ul>
    
<nav class="teal-white">
<div class="container" style="width:100%;border:0px solid red;">
<div class="nav-wrapper">    

  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
  <?php
  function adminMenu($menu_id='nav-mobile',$class="left hide-on-med-and-down"){
  	
  	
  return  array( 
     'id' => $menu_id,
     'htmlOptions'=>array(
       'class'=>$class
     ),
     'activeCssClass'=>'active', 
     'encodeLabel'=>false,
     'items'=>array(
        array('visible'=>true,'label'=>t('Dashboard'),
        'url'=>array('/admin/dashboard'),'linkOptions'=>array()),               
        
        array('visible'=>true,'label'=>t('Plan'),
        'url'=>array('/admin/plan-list'),'linkOptions'=>array()),               
        
        array('visible'=>true,'label'=>t('Customer'),
        'url'=>array('/admin/customer-list'),'linkOptions'=>array()),               
                
        array('visible'=>true,'label'=>t('Payment'),
        'url'=>array('/admin/payment-list'),'linkOptions'=>array()),               

        array('visible'=>true,'label'=>t('Promo'),
        'url'=>array('/admin/promocode'),'linkOptions'=>array()),                      
        
        array('visible'=>true,'label'=>t('SMS'),
        'url'=>array('/admin/sms'),'linkOptions'=>array()),               

        array('visible'=>true,'label'=>t('Currency'),
        'url'=>array('/admin/currency'),'linkOptions'=>array()),               
        
        array('visible'=>true,'label'=>t('Services'),
        'url'=>array('/admin/services'),'linkOptions'=>array()),                
        
       array('visible'=>true,'label'=>t('SEO'),
        'url'=>array('/admin/seo'),'linkOptions'=>array()),                 
                              
        array('visible'=>true,'label'=>t('General Settings'),
        'url'=>array('/admin/settings'),'linkOptions'=>array()),               
        
       array('visible'=>true,'label'=>t('Mobile Settings'),
        'url'=>array('/admin/mobilesettings'),'linkOptions'=>array()), 
        
        array('visible'=>true,'label'=>t('Maps'),
        'url'=>array('/admin/map_settings'),'linkOptions'=>array()),  
        
        array('visible'=>true,'label'=>t('Page'),
        'url'=>array('/admin/custompage'),'linkOptions'=>array()),  
                
        array('visible'=>true,'label'=>t('Templates'),
        'url'=>array('/admin/templates'),'linkOptions'=>array()),
        
        array('visible'=>true,'label'=>t('Language'),
        'url'=>array('/admin/language'),'linkOptions'=>array()),
        
        array('visible'=>true,'label'=>t('Cron'),
        'url'=>array('/admin/cron'),'linkOptions'=>array()),
        
        /*array('visible'=>true,'label'=>t('Map Logs'),
        'url'=>array('/admin/api_logs'),'linkOptions'=>array()),*/
        
        array('visible'=>true,'label'=>t('API'),
        'url'=>array('/admin/api'),'linkOptions'=>array()),
        
     )
  );
  }
  ?>
  <?php $this->widget('zii.widgets.CMenu', adminMenu());?>

  <?php $this->widget('zii.widgets.CMenu', adminMenu('mobile-demo','side-nav') );?>
   
</div>
</div>
</nav>

protected/views/admin/plans.php
<div class="card">
 <div class="card-content">
   
 
  <div class="row">
    <div class="col s6">
      <h5><?php echo t("Plans")?></h5>
    </div>
    <div class="col s6 right-align">
     <a href="<?php echo Yii::app()->createUrl('/admin/plan-new')?>" class="btn-floating btn-small waves-effect waves-light">
        <i class="material-icons">add</i>
      </a>
      
      <a href="<?php echo Yii::app()->createUrl('/admin/plan-list')?>" class="btn-floating btn-small waves-effect waves-light">
        <i class="material-icons">replay</i>
      </a>
    </div>
  </div> <!--row-->
 
  
   <form id="frm" method="POST" onsubmit="return false;">
   <?php echo CHtml::hiddenField('action','addPlans')?>
   <?php if (isset($data['plan_id'])):?>
   <?php echo CHtml::hiddenField('id',$data['plan_id'])?>
   <?php endif;?>   
   
   <?php if (isset($_GET['msg'])):?>
   <?php echo CHtml::hiddenField('msg',$_GET['msg'])?>
   <?php endif;?>   
   
   <div class="input-field">
	      <?php echo CHtml::textField('plan_name',
	      isset($data['plan_name'])?$data['plan_name']:''
	      ,array('class'=>"validate",
	      'data-validation'=>"required"
	      ))?>
	      <label for="plan_name"><?php echo t("Plan name")?></label>
   </div>
   
    <div class="input-field">
	      <?php echo CHtml::textArea('plan_name_description',
	      isset($data['plan_name_description'])?$data['plan_name_description']:''
	      ,array('class'=>"materialize-textarea",
	      //'data-validation'=>"required"
	      ))?>
	      <label for="plan_name_description"><?php echo t("Description")?></label>
   </div>
   
   <div class="row">
    <div class="col s6">
   
	   <div class="input-field">
	      <?php echo CHtml::textField('price',
	      isset($data['price'])?normalPrettyPrice($data['price']):''
	      ,
	       array(
	        'class'=>"validate numeric_only",
	        'data-validation'=>"required"
	      ))?>
	      <label><?php echo t("Price")?></label>
	   </div>
   
    </div>
   
    <div class="col s6">

	   <div class="input-field">
	      <?php echo CHtml::textField('promo_price',
	      isset($data['promo_price'])?$data['promo_price']>0?normalPrettyPrice($data['promo_price']):'':''
	      ,
	       array(
	        'class'=>"validate numeric_only",	       
	      ))?>
	      <label><?php echo t("Promo Price")?></label>
	   </div>

    </div>
   </div><!-- row-->
   
    <div class="row">
     <div class="col s6">
         <div class="input-field">
            <?php echo CHtml::dropDownList('plan_type',
            isset($data['plan_type'])?$data['plan_type']:''
            ,array(
              'days'=>t("Day"),
              'month'=>t("Month"),
              'year'=>t("Year"),
            ))?>
		    <label><?php echo t("Type")?></label>
         </div>
     </div> <!--col-->
     <div class="col s6">
         <div class="input-field">
	      <?php echo CHtml::textField('expiration',
	      isset($data['expiration'])?$data['expiration']:''
	      ,
	       array(
	        'class'=>"validate numeric_only",
	        'data-validation'=>"required"
	      ))?>
	      <label><?php echo t("Expiration")." ".t("number of days/month/year")?></label>
	   </div>
     </div> <!--col-->
    </div> <!--row-->
    
    <div class="row">
	    <div class="col s6">
	    <div class="input-field">
	        <?php echo CHtml::dropDownList('allowed_driver',
	        isset($data['allowed_driver'])?$data['allowed_driver']:''
	        ,array(
	          'unlimited'=>t("unlimited"),
	          1=>1,
	          2=>2,
	          3=>3,
	          4=>4,         
	          5=>5,
	          6=>6,
	          7=>7,
	          8=>8,
	          9=>9,
	          10=>10,
	        ))?>
		    <label><?php echo t("Number of allowed driver")?></label>
	    </div>
	    </div>
	    
	    <div class="col s6">
	    <div class="input-field">
	        <?php echo CHtml::dropDownList('allowed_task',
	        isset($data['allowed_task'])?$data['allowed_task']:''
	        ,array(
	          'unlimited'=>t("unlimited"),
	          1=>1,
	          2=>2,
	          3=>3,
	          4=>4,
	          5=>5,
	          10=>10,
	          20=>20,
	          30=>30,
	          40=>40,         
	          50=>50,
	          60=>60,
	          70=>70,
	          80=>80,
	          90=>90,
	          100=>100,     
	          200=>200,
	          300=>300,
	          400=>400,
	          500=>500,
	        ))?>
		    <label><?php echo t("Number of allowed task")?></label>
	    </div>
	    </div>
    </div> <!--row-->
    
    
    <div class="row">
    <div class="col s6">
    <p>
      <?php echo CHtml::checkBox('with_sms',
      isset($data['with_sms'])?$data['with_sms']==1?true:false:''
      ,array(
       'value'=>1
      ))?>      
      <label for="with_sms"><?php echo t("With SMS Notification")?></label>
    </p>
    </div>
    
    <div class="col s6">
      <div class="input-field">
	      <?php echo CHtml::textField('sms_limit',
	      isset($data['sms_limit'])?$data['sms_limit']:''
	      ,
	       array(
	        'class'=>"validate numeric_only",
	        //'data-validation'=>"required"
	      ))?>
	      <label><?php echo t("SMS Limit")?></label>
	   </div>
    </div>    
    </div>
    
    <div class="row">
    <div class="col s6">
    <p>
      <?php echo CHtml::checkBox('with_broadcast',
      isset($data['with_broadcast'])?$data['with_broadcast']==1?true:false:''
      ,array(
       'value'=>1
      ))?>      
      <label for="with_broadcast"><?php echo t("With Push Broadcast")?></label>
    </p>
    </div>
    </div>
    
    <div class="row">
    <div class="col s12">
    <div class="input-field">
        <?php echo CHtml::dropDownList('status',
        isset($data['status'])?$data['status']:''
        ,AdminFunctions::statusList())?>
	    <label><?php echo t("Status")?></label>
    </div>
    </div>
    </div>
    
     <div class="card-action" style="margin-top:20px;">
     <button class="btn waves-effect waves-light" type="submit" name="action">
       <?php echo t("Submit")?>
     </button>
     </div>
         
   
   </form>
         
  
 </div>
</div> 

protected/views/admin/rpt-sales.php
<form id="frm_table" method="POST" onsubmit="return false;">
<?php echo CHtml::hiddenField('action','rptSales');?>

 <ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">zoom_in</i><?php echo t("Filter")?></div>
    <div class="collapsible-body">
    
    <div class="row" style="padding:0 20px;">
       <div class="col s3">
         <div class="input-field">	    
	     <?php echo CHtml::textField('start_date',
	     ''
	     ,array('class'=>"datepicker",	  
	     'data-validation'=>'required'
	     ))?>
	     <label><?php echo t("Start Date")?></label>
	   </div>  
       </div>
       <div class="col s3">
         <div class="input-field">	    
	     <?php echo CHtml::textField('end_date',
	     ''
	     ,array('class'=>"datepicker ",	     
	     'data-validation'=>'required'
	     ))?>
	     <label><?php echo t("End Date")?></label>
	   </div>  
       </div>
       
       <div class="col s3">
	     <button class="btn waves-effect waves-light" type="submit" name="action" style="margin-top: 18px;">
	       <?php echo t("Submit")?>
	     </button>
       </div>
       
    </div>
        
    </div>
  </li>
</ul>  
  
<div class="card">
 <div class="card-content">
   
  <div class="row">
    <div class="col s6">
      <h5><?php echo t("Sales report")?></h5>
    </div>
    <div class="col s6 right-align">
    
     <a target="_blank" class="waves-effect blue lighten-1 btn" href="<?php echo Yii::app()->createUrl('admin/export',array(
      'filename'=>'sales_report'
     ))?>" >
     <i class="material-icons left">import_export</i> <?php echo t("Export")?>
     </a>  
    
    </div>
  </div> <!--row-->
     
  
   <table id="table_list" class="bordered highlight responsive-table">
    <thead>
      <tr>
       <th width="8%"><?php echo t("Date")?></th>
       <th width="5%"><?php echo t("Trans Type")?></th>
       <th width="10%"><?php echo t("Payment Provider")?></th>
       <th width="10%"><?php echo t("Memo")?></th>
       <th width="5%"><?php echo t("Total")?></th>
       <th width="10%"><?php echo t("Transaction Ref")?></th>                
      </tr>
    </thead>
    <tbody>     
    </tbody>
   </table> 
   
  
  
 </div> <!--card-content-->
</div> <!--card-->

</form>

<style type="text/css">
#table_list_filter{
display:none;
}
</style>