protected/controllers/InstallController.php
<?php
if (!isset($_SESSION)) { session_start(); }

class InstallController extends CController
{
	public $layout='install_layout';	
	
	
	public function beforeAction($action)
	{
		$cs = Yii::app()->getClientScript();
		$baseUrl = Yii::app()->baseUrl.""; 
		
		Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/jquery-1.10.2.min.js',
		CClientScript::POS_END
		);
		
		Yii::app()->clientScript->registerScriptFile(
        "//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js",
		CClientScript::POS_END
		);			
		$cs->registerCssFile("//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css");
        $cs->registerCssFile("//fonts.googleapis.com/icon?family=Material+Icons");		 
                
        if (AdminFunctions::checkIfTableExist('option')){
        	$installation_done = Yii::app()->functions->getOptionAdmin('installation_done');
        	if($installation_done==1){        		
				return false;
			}
        }
        return true;
	}
	
	public function actionIndex()
	{
		$this->render('install');
	}
	
	public function actionStep2()
	{
		if($_SESSION['kt_install']==1){		   
		   $this->render('install_step2');
		} else $this->redirect(Yii::app()->createUrl('/install/index',array(
		 'error'=>"Session install not found"
		)));
	}
	
	public function actionstep3()
	{
		$this->render('install_step3');
	}
	
	public function actionfinish()
	{
		$encryption_type=Yii::app()->params->encryption_type;
		if(empty($encryption_type)){
			$encryption_type='yii';
		}
				
		$data=$_POST;				
		if(isset($data['username'])){			
		   $db_ext=new DbExt;

		   $db_ext->qry("TRUNCATE TABLE {{admin}}");
		    
		   $params=array(
		     'first_name'=>'admin',
		     'last_name'=>'admin',
		     'username'=>$data['username'],
		     //'password'=>CPasswordHelper::hashPassword($data['password']),
		     'date_created'=>AdminFunctions::dateNow(),
		     'date_modified'=>AdminFunctions::dateNow(),
		     'last_login'=>AdminFunctions::dateNow(),
		     'ip_address'=>$_SERVER['REMOTE_ADDR']
		   );		   
		   		   
		   if ( $encryption_type=="md5"){  
		   	   $params['password']=md5($data['password']);
		   } else {
		   	   $params['password']=CPasswordHelper::hashPassword($data['password']);
		   }
		   
		   $db_ext->insertData("{{admin}}",$params);
		   		   	
		   $db_ext->qry("TRUNCATE TABLE {{option}}");
		   
		    $db_ext->insertData("{{option}}",array(
		     'option_name'=>'company_name',
		     'option_value'=>$data['company_name']
		    ));
		   	    
		   $this->installData();
		   
		   $this->render('finish',array(
		     'code'=>1
		   ));
		} else $this->render('finish',array(
		   'code'=>2,
		   'msg'=>"Missing required information"
		));
	}
	
	private function installData()
	{
		$db_ext=new DbExt;
		
		
		$db_ext->insertData("{{option}}",array(
		     'option_name'=>'installation_done',
		     'option_value'=>1
		 ));
		 		 
		 
		$db_ext->insertData("{{option}}",array(
		     'option_name'=>'forgot_password_tpl',
		     'option_value'=>"hi [first_name]

your verification code is : [verification_code]


cheers"
		 ));
		 
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'signup_tpl_sms',
	     'option_value'=>"your sms verification code is [verification_code]"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'signup_tpl_email',
	     'option_value'=>"hi [first_name]

your email verification code is [verification_code]

Regards"
	    ));
	    	    	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'signup_tpl_email_subject',
	     'option_value'=>"Your Signup Verification code"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'forgot_password_subject',
	     'option_value'=>"You have requested for your password"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'welcome_tpl_subject',
	     'option_value'=>"Welcome [first_name]"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'currency_decimal_places',
	     'option_value'=>2
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'approved_tpl_subject',
	     'option_value'=>"Your account has been approved"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'approved_tpl',
	     'option_value'=>"Hi [first_name]

your account is approved
username : [username]
password : your password

you can login here [login_link]

cheers"
	    ));
	    
	    $db_ext->insertData("{{currency}}",array(	     
	        'currency_code'=>"USD",
	        'currency_symbol'=>"$",
	        'status'=>"published",
	        'date_created'=>AdminFunctions::dateNow(),
	        'date_modified'=>AdminFunctions::dateNow(),
	        'ip_address'=>$_SERVER['REMOTE_ADDR']
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'website_currency',
	     'option_value'=>1
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'welcome_tpl',
	     'option_value'=>"hi [first_name]

Thank you for signup 


thanks
"
	    ));
	    
	    $db_ext->insertData("{{option}}",array(
	     'option_name'=>'email_provider',
	     'option_value'=>"php_mail"
	    ));
	    
	    
	    if ( !$i=$db_ext->rst("SELECT * FROM {{services}} LIMIT 0,1")){		
			$path=Yii::getPathOfAlias('webroot')."/protected";
            require_once($path.'/config/services_data.php');
			$db_ext->qry($services);	
		} 
	    	   
	}
	
} /*end class*/

protected/views/install/finish.php
<nav class="teal lighten-1">
<div class="nav-wrapper">
  <a href="<?php echo Yii::app()->createUrl('/install/index')?>">
     <img style="margin-top: 5px;margin-left: 20px;" class="logo" src="<?php echo Yii::app()->getBaseUrl(true)."/assets/images-front/logo.png"?>">     
  </a>       
</div>
</nav>
  
<form method="POST" onsubmit="return checkform();" action="<?php echo Yii::app()->createUrl('install/finish')?>">
<div class="container">
   <div style="margin-top:30px;">

    <div class="card">
      
	  <nav class="teal lighten-1">
	    <div class="nav-wrapper">
	      <div class="col s12" style="padding-left:20px;">
	        <a href="<?php echo Yii::app()->createUrl('install')?>" class="breadcrumb">Checking requirements</a>
	        <a href="#!" class="breadcrumb">Database Tables</a>
	        <a href="#!" class="breadcrumb">Website Information</a>
	        <a href="#!" class="breadcrumb">Finish</a>
	      </div>
	    </div>
	  </nav>        
	  
	  <div class="card-content">
	  
	   <?php if($code==1):?>
	   <h4>Installation done...</h5>
	   
	   <?php $base=Yii::app()->getBaseUrl(true);?>
	   <p>Admin link</p>
	   <a href="<?php echo $base?>/admin" target="_blank"><?php echo $base?>/admin</a>
	   
	   <p style="margin-top:10px">Front link</p>
	   <a href="<?php echo $base?>/" target="_blank"><?php echo $base?>/</a>
	   
	   <p style="margin-top:10px">Customer app link</p>
	   <a href="<?php echo $base?>/app" target="_blank"><?php echo $base?>/app</a>
	   
	   <p style="color:red;margin-top:50px;">
	   Important : For security purposes you can delete or rename the file controllers/InstallController.php
	   </p>
	   
	   <?php else :?>
	   <h4>Installation has failed.</h5>
	   <p style="color:red;"><?php echo $msg;?></p>
	   <p style="margin-top:50px;"><a href="<?php echo Yii::app()->createUrl('install/')?>">CLick here</a> to install again</p>
	   <?php endif;?>
	  
	  </div> <!--card-content-->
	  	    
		
	  
	</div> <!--card--> 
 
   </div> <!--top30-->	 
</div> <!--container-->
</form>

protected/views/install/install.php
<?php 
$failed=0;
$_SESSION['kt_install']=2;
$path=Yii::getPathOfAlias('webroot');
?>

<nav class="teal lighten-1">
<div class="nav-wrapper">
  <a href="<?php echo Yii::app()->createUrl('/install/index')?>">
     <img style="margin-top: 5px;margin-left: 20px;" class="logo" src="<?php echo Yii::app()->getBaseUrl(true)."/assets/images-front/logo.png"?>">     
  </a>       
</div>
</nav>
  
<form method="POST" action="<?php echo Yii::app()->createUrl('install/step2')?>">
<div class="container">
   <div style="margin-top:30px;">
   
   <div class="card">
   
   <nav class="teal lighten-1">
    <div class="nav-wrapper">
      <div class="col s12" style="padding-left:20px;">
        <a href="<?php echo Yii::app()->createUrl('install')?>" class="breadcrumb">Checking requirements</a>        
      </div>
    </div>
   </nav>    
   
   <div class="card-content">
    <p>
	   <?php
		try {
	        echo 'Connecting to database...<br/>';
	        $connection = Yii::app()->db;  // (*)
	        echo ($connection ? 'Database Successful [OK]' : 'Database Failed');
		}
		catch(Exception $ex) {
		    echo $ex->getMessage();
		    $failed++;
		}
	   ?>
    </p>
    
    <p>
    <?php 
    if (!defined('PDO::ATTR_DRIVER_NAME')){    	
    	echo "PDO is not installed";
    	$failed++;
    } else echo "PDO installed [OK]";
    ?>
    </p>
    
    <p>
    <?php 
    $_SESSION['test']='test';
    if (!empty($_SESSION['test'])){
    	echo "Session [OK]";
    } else {
    	echo "Session not supported";
    	$failed++;
    }
    ?>
    </p>
    
    <p>
    <?php 
    if ( !function_exists( 'mail' ) ) { 
    	echo "mail() has been disabled";
    	$failed++;
    } else echo "mail() is available [OK]"	;
    ?>
    </p>
    
    <p>
    <?php 
    if ( function_exists('curl_version') ){
    	echo "CURL is enabled [OK]";
    } else {
    	echo "CURL is disabled";
    	$failed++;
    }
    ?>
    </p>
    
    <p>
    <?php 
    if ( @file_get_contents(__FILE__) ){
    	echo "file_get_contents is enabled [OK]";
    } else {
    	echo "file_get_contents is disabled";
    	$failed++;
    }
    ?>
    </p>
    
    <p>    
    <?php 
    //$isEnabled = in_array('mod_rewrite', apache_get_modules());
    $isEnabled=true;
    echo ($isEnabled) ? 'mod_rewrite Enabled' : 'mod_rewrite Not enabled';
    if(!$isEnabled){
    	$failed++;
    }
    ?>
    </p>
    
    <p>
    <?php 
    $encryption_type=Yii::app()->params->encryption_type;    
    if($encryption_type=="yii"):
	    if ( !function_exists( 'mcrypt_module_get_supported_key_sizes' ) ) { 
	    	echo "mcrypt_module_get_supported_key_sizes is not available in your server please change the encryption_type to md5 in your main.php";
	    	$failed++;
	    } else echo "mcrypt_module_get_supported_key_sizes is available [OK]"	;
    endif;
    ?>
    </p>
    
    <p>
    <?php 
    $t_path=explode("/",$path);        
    $host=dirname($_SERVER['REQUEST_URI']);
    $host=$host=="/"?"":$host;
    $current_dir_folder=$host;
    $ht_file=$path."/.htaccess";    
    if(!file_exists($ht_file)){
    	echo 'Creating .htaccess file<br/>';    
    	if ( $host=="htdocs" || $host=="public_html" || $host==""){
$htaccess="<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>";  	
} else {  
$htaccess="<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase $current_dir_folder/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . $current_dir_folder [L]
</IfModule>";
}
		InstallHelper::dump($htaccess);
		InstallHelper::createFile($ht_file,$htaccess);
    }
    ?>    
    </p>
    
    
    <p>
    <?php 
    if ( $failed<=0){
    	$_SESSION['kt_install']=1;
    	echo '<h5>Everything seems to be ok. Proceed to next steps</h5>';
    } else echo '<h5 style="color:red;font-size:16px;">There seems to be error in checking your server. Please fixed the following issue and try again.</h5>';
    ?>
    </p>
    
    </div>  <!--card-content-->
   
     <?php if($_SESSION['kt_install']==1):?>
	 <div class="card-action" style="margin-top:20px;">
	 <button class="btn waves-effect waves-light" type="submit" name="action">
	   Install
	 </button>
	 </div>
	 <?php endif;?>
	 
  </div> <!--card-->
   
  </div>	 
</div> <!--container-->
</form>

protected/views/install/install_step2.php
<?php 
$table_prefix=Yii::app()->db->tablePrefix;
$DbExt=new DbExt;

$path=Yii::getPathOfAlias('webroot')."/protected";
require_once($path.'/config/table_structure.php');
?>

<nav class="teal lighten-1">
<div class="nav-wrapper">
  <a href="<?php echo Yii::app()->createUrl('/install/index')?>">
     <img style="margin-top: 5px;margin-left: 20px;" class="logo" src="<?php echo Yii::app()->getBaseUrl(true)."/assets/images-front/logo.png"?>">     
  </a>       
</div>
</nav>
  
<form method="POST" action="<?php echo Yii::app()->createUrl('install/step3')?>">
<div class="container">
   <div style="margin-top:30px;">
     
   <div class="card">
      
  <nav class="teal lighten-1">
    <div class="nav-wrapper">
      <div class="col s12" style="padding-left:20px;">
        <a href="<?php echo Yii::app()->createUrl('install')?>" class="breadcrumb">Checking requirements</a>
        <a href="#!" class="breadcrumb">Database Tables</a>
        <!--<a href="#!" class="breadcrumb">Finish</a>-->
      </div>
    </div>
  </nav>            
   
    <div class="card-content">
 
    <h5>Creating database tables...</h5>
    
    <p>
    <?php $x=1;?>
    <?php foreach ($tbl as $key=>$val) {    	    	
    	echo "Creating table $key [OK]<br/>";
    	$DbExt->qry($val);
    	$x++;
    }?>
    </p>
    
    </div>  <!--card-content-->
   
     <?php if($_SESSION['kt_install']==1):?>
	 <div class="card-action" style="margin-top:20px;">
	 <button class="btn waves-effect waves-light" type="submit" name="action">
	   Next
	 </button>
	 </div>
	 <?php endif;?>
	 
  </div> <!--card-->
   
  </div>	 
</div> <!--container-->
</form>

protected/views/install/install_step3.php
<nav class="teal lighten-1">
<div class="nav-wrapper">
  <a href="<?php echo Yii::app()->createUrl('/install/index')?>">
     <img style="margin-top: 5px;margin-left: 20px;" class="logo" src="<?php echo Yii::app()->getBaseUrl(true)."/assets/images-front/logo.png"?>">     
  </a>       
</div>
</nav>
  
<form method="POST" onsubmit="return checkform();" action="<?php echo Yii::app()->createUrl('install/finish')?>">
<div class="container">
   <div style="margin-top:30px;">

    <div class="card">
      
	  <nav class="teal lighten-1">
	    <div class="nav-wrapper">
	      <div class="col s12" style="padding-left:20px;">
	        <a href="<?php echo Yii::app()->createUrl('install')?>" class="breadcrumb">Checking requirements</a>
	        <a href="#!" class="breadcrumb">Database Tables</a>
	        <a href="#!" class="breadcrumb">Website Information</a>
	      </div>
	    </div>
	  </nav>        
	  
	  <div class="card-content">
	  
	  <div class="row">
	    <div class="col m6">	    
	       <div class="input-field">
		      <?php echo CHtml::textField('company_name',
		      ''
		      ,
		       array(
		        'class'=>"validate",
		        'data-validation'=>"required"
		      ))?>
		      <label>Website Name</label>
		   </div>      	    
	    </div> <!--col-->	    
	  </div> <!--row-->
	  
	 
	  <div class="row">
	    <div class="col m6">	    
	       <div class="input-field">
		      <?php echo CHtml::textField('username',
		      ''
		      ,
		       array(
		        'class'=>"validate",
		        'data-validation'=>"required"
		      ))?>
		      <label>Username</label>
		   </div>      	    
	    </div> <!--col-->	    
	    <div class="col m6">	    
	       <div class="input-field">
		      <?php echo CHtml::passwordField('password',
		      ''
		      ,
		       array(
		        'class'=>"validate",
		        'data-validation'=>"required"
		      ))?>
		      <label>Password</label>
		   </div>      	    
	    </div> <!--col-->	 
	  </div> <!--row-->  
	  
	  </div> <!--card-content-->
	  	    
		 <div class="card-action" style="margin-top:20px;">
		 <button class="btn waves-effect waves-light" type="submit" name="action">
		   Next
		 </button>
		 </div>	 
	  
	</div> <!--card--> 
 
   </div> <!--top30-->	 
</div> <!--container-->
</form>

<script type="text/javascript">
function checkform()
{
	var err='';
	
	if ( $("#company_name").val()=="" ){
		err="Company name is required \n";
	}
	if ( $("#username").val()=="" ){
		err+="Username name is required \n";
	}
	if ( $("#password").val()=="" ){
		err+="Password name is required \n";
	}
	
	if(err==""){
	   return true;
	}
	alert(err);
	return false;
}
</script>