protected/controllers/AppController.php
<?php
if (!isset($_SESSION)) { session_start(); }

class AppController extends CController
{
	public $layout='layout';	
	public $body_class='';
	
	public function init()
	{			
		 // set website timezone
		 $website_timezone=Yii::app()->functions->getOptionAdmin("website_timezone" );		 
		 if (!empty($website_timezone)){		 	
		 	Yii::app()->timeZone=$website_timezone;
		 }	

		 $customer_timezone=getOption( Driver::getUserId(), 'customer_timezone');
		 if (!empty($customer_timezone)){
		 	Yii::app()->timeZone=$customer_timezone;
		 }
		 
		 /*dump(Yii::app()->timeZone);
		 dump(date('c'));
		 die();*/
		 		 
		 if(isset($_GET['lang'])){
		 	Yii::app()->language=$_GET['lang'];
		 }
	}
	
	public function beforeAction($action)
	{		
		/*if (Yii::app()->controller->module->require_login){
			if(! DriverModule::islogin() ){
			   $this->redirect(Yii::app()->createUrl('/admin/noaccess'));
			   Yii::app()->end();		
			}
		}*/
		$action_name= $action->id ;
		$accept_controller=array('login','ajax','resetpassword');
		if(!Driver::islogin()){			
			if(!in_array($action_name,$accept_controller)){
				$this->redirect(Yii::app()->createUrl('/app/login'));
			}
		}
		
		
		/*check user status*/
		$status=Driver::getUserStatus();
		if($status=="expired"){
			if($action_name!="profile"){
				if($action_name!="logout"){
				$this->redirect(Yii::app()->createUrl('/app/profile',array(
				  'tabs'=>2
				)));
				Yii::app()->end();
				}
			}
		}
		
		ScriptManager::scripts();
		
		$cs = Yii::app()->getClientScript();
		$jslang=json_encode(Driver::jsLang());
		$cs->registerScript(
		  'jslang',
		 "var jslang=$jslang;",
		  CClientScript::POS_HEAD
		);
				
		$js_lang_validator=Yii::app()->functions->jsLanguageValidator();
		$js_lang=Yii::app()->functions->jsLanguageAdmin();
		$cs->registerScript(
		  'jsLanguageValidator',
		  'var jsLanguageValidator = '.json_encode($js_lang_validator).'
		  ',
		  CClientScript::POS_HEAD
		);				
		$cs->registerScript(
		  'js_lang',
		  'var js_lang = '.json_encode($js_lang).';
		  ',
		  CClientScript::POS_HEAD
		);
		
		$cs->registerScript(
		  'account_status',
		 "var account_status='$status';",
		  CClientScript::POS_HEAD
		);
		
		$language=Yii::app()->language;
		$cs->registerScript(
		  'language',
		 "var language='$language';",
		  CClientScript::POS_HEAD
		);
		
		$calendar_language=getOption( Driver::getUserId(), 'calendar_language');
		$cs->registerScript(
		  'calendar_language',
		 "var calendar_language='$calendar_language';",
		  CClientScript::POS_HEAD
		);
		
		$map_hide_pickup=getOption( Driver::getUserId(), 'map_hide_pickup');
		$cs->registerScript(
		  'map_hide_pickup',
		 "var map_hide_pickup='$map_hide_pickup';",
		  CClientScript::POS_HEAD
		);
		
		$map_hide_pickup=getOption( Driver::getUserId(), 'map_hide_delivery');
		$cs->registerScript(
		  'map_hide_delivery',
		 "var map_hide_delivery='$map_hide_pickup';",
		  CClientScript::POS_HEAD
		);
		
		$map_hide_pickup=getOption( Driver::getUserId(), 'map_hide_success_task');
		$cs->registerScript(
		  'map_hide_success_task',
		 "var map_hide_success_task='$map_hide_pickup';",
		  CClientScript::POS_HEAD
		);
		
		$auto_geo_address=getOption( Driver::getUserId(), 'driver_auto_geo_address');
		$cs->registerScript(
		  'auto_geo_address',
		 "var auto_geo_address='$auto_geo_address';",
		  CClientScript::POS_HEAD
		);
		
		$driver_activity_tracking=getOption( Driver::getUserId(), 'driver_activity_tracking');		
		$cs->registerScript(
		  'disabled_activity_tracking',
		 "var disabled_activity_tracking='$driver_activity_tracking';",
		  CClientScript::POS_HEAD
		);
		
		$driver_activity_tracking_interval=getOption( Driver::getUserId(), 'driver_activity_tracking_interval');				
		if($driver_activity_tracking_interval<=0){
			$driver_activity_tracking_interval=60;
		}
		$driver_activity_tracking_interval = $driver_activity_tracking_interval*1000;
		$cs->registerScript(
		  'activity_tracking_interval',
		 "var activity_tracking_interval='$driver_activity_tracking_interval';",
		  CClientScript::POS_HEAD
		);
		
		$rr_days = json_encode(Driver::returnDays());
		$cs->registerScript(
		  'rr_days',
		 "var rr_days='".CJavaScript::quote($rr_days)."';",
		  CClientScript::POS_HEAD
		);
		
		$rr_repetion = json_encode(Driver::returnTaskRepetition());
		$cs->registerScript(
		  'rr_repetion',
		 "var rr_repetion='".CJavaScript::quote($rr_repetion)."';",
		  CClientScript::POS_HEAD
		);
						
		if($action_name=="index" || $action_name=="contacts"){
			$map_provider = getOptionA('map_provider');
			if($map_provider=="mapbox"){
				$site_url=Yii::app()->baseUrl.'/';
				Yii::app()->clientScript->registerCssFile($site_url."/assets/leaflet/plugin/routing/leaflet-routing-machine.css");
				Yii::app()->clientScript->registerScriptFile($site_url."/assets/leaflet/plugin/routing/leaflet-routing-machine.min.js"
				,CClientScript::POS_END); 
			}
		}
				
		return true;				
	}
	
	public function actionLogin()
	{
		
		$encryption_type=Yii::app()->params->encryption_type;
		if(empty($encryption_type)){
			$encryption_type='yii';
		}
		
		if(Driver::islogin()){						
		    $this->redirect(Yii::app()->createUrl('/app'));			
		    Yii::app()->end();
		}
		
		$this->body_class='login-body';
		
		/*unset(Yii::app()->request->cookies['kt_username']);
		unset(Yii::app()->request->cookies['kt_password']);*/
		
		$kt_username = isset(Yii::app()->request->cookies['kt_username']) ? Yii::app()->request->cookies['kt_username']->value : '';
		$kt_password = isset(Yii::app()->request->cookies['kt_password']) ? Yii::app()->request->cookies['kt_password']->value : '';
		
		if ($encryption_type=="yii"){
			if(!empty($kt_password) && !empty($kt_username)){
			   $kt_password=Yii::app()->securityManager->decrypt( $kt_password );		
			}
		} else $kt_password='';
		
		$this->render('login',array(
		  'email_address'=>$kt_username,
		  'password'=>$kt_password
		));
	}
	
	public function actionLogout()
	{
		unset($_SESSION['mobilogrd']);
		$this->redirect(Yii::app()->createUrl('/app/login'));
	}
	
	public function actionIndex(){		
		$this->body_class="dashboard";		
		$this->render('dashboard');
	}	
	
	public function actionDashboard()
	{
		$this->body_class="dashboard";		
		$this->render('dashboard');
	}

	public function actionAgents()
	{
		$this->body_class="page-single";	
		$this->render('agents-list');
	}
	
	public function actionTasks()
	{
		$this->body_class="page-single";	
		$this->render('task-list');
	}
	
	public function actionSettings()
	{		
				
        $country_list=require_once('CountryCode.php');
        $this->body_class='settings-page';
                     
        if ( Driver::getUserType()=="merchant"){
        	$this->render('error',array(
        	  'msg'=>Driver::t("Sorry but you don't have access to this page")
        	));
        } else {
        	
        	$language_list=getOptionA('language_list');
			if(!empty($language_list)){
			   $language_list=json_decode($language_list,true);	
			}   
			$action_name=Yii::app()->controller->action->id;
        	
			if(is_array($language_list) && count($language_list)>=1){
			   array_unshift($language_list,t("Please select"));
			}
			
			$this->render('settings',array(			  
			  'country_list'=>$country_list,
			  'language_list'=>$language_list,
			  'action_name'=>$action_name
			));
        }
	}
	
	public function actionTeams()
	{
		$this->body_class="page-single";	
		$this->render('teams');
	}
	
	public function actionlanguage()
	{
		$lang=Driver::availableLanguages();		
		$dictionary=require_once('MobileTranslation.php');		
		
		$mobile_dictionary=getOptionA('driver_mobile_dictionary');
        if (!empty($mobile_dictionary)){
	       $mobile_dictionary=json_decode($mobile_dictionary,true);
        } else $mobile_dictionary=false;
		
		$this->render('language',array(
		  'lang'=>$lang,
		  'dictionary'=>$dictionary,
		  'mobile_dictionary'=>$mobile_dictionary
		));
	}
	
	public function actionNotifications()
	{
		$this->body_class="page-single";
		$this->render('notifications');
	}
	
	public function actionPushlogs()
	{
		$this->body_class="page-single";
		$this->render('push-logs',array(
		  'broadcast_id'=>isset($_GET['broadcast_id'])?$_GET['broadcast_id']:""
		));
	}
		
	public function actionReports()
	{
		$this->body_class="page-single";
		$cs = Yii::app()->getClientScript(); 
		
		Yii::app()->clientScript->registerScriptFile(
		Yii::app()->baseUrl . '/assets/amcharts/amcharts.js'
        ,CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/serial.js',
        CClientScript::POS_END);		
        
        Yii::app()->clientScript->registerScriptFile(
        Yii::app()->baseUrl . '/assets/amcharts/themes/light.js',
        CClientScript::POS_END);		
		
        $team_list=Driver::teamList( Driver::getUserId());
		if($team_list){
			 $team_list=Driver::toList($team_list,'team_id','team_name',
			   Driver::t("All Team")
			 );
		}
		
		$all_driver=Driver::getAllDriver(
           Driver::getUserId()
        );   

        $start= date('Y-m-d', strtotime("-7 day") );
	    $end=date("Y-m-d", strtotime("+1 day")); 
        
		$this->render('reports',array(
		  'team_list'=>$team_list,
		  'all_driver'=>$all_driver,
		  'start_date'=>$start,
		  'end_date'=>$end
		));
	}
	
	public function actionAssignment()
	{
		$this->body_class="page-single";
		$this->render('assignment');
	}
	
	public function actionResetPassword()
	{
		$this->body_class='login-body';		
		$this->render('resetpassword',array(
		 'hash'=>isset($_GET['hash'])?$_GET['hash']:''
		));
	}
	
	public function actionprofile()
	{
		
		FrontFunctions::ClearPromoCode();
				
		$this->body_class="page-single";
		if($data=AdminFunctions::getCustomerByID( Driver::getUserId())){				
			$plans=Driver::getPlansByID( $data['plan_id']);			
			$this->render('profile',array(
			  'data'=>$data,
			  'plans'=>$plans,

protected/views/tpl/layout1_top.php
<!-- <?php 
$team_list=Driver::teamList( Driver::getUserId());
if($team_list){
	 $team_list=Driver::toList($team_list,'team_id','team_name',
	   Driver::t("All Team")
	 );
}
?> -->
<div class="container-fluid border">
<div class="row top grey-top-header">
  <div class="col-sm-4 border" >
  
    <div class="search-team-wrap">
    
    <!-- <div class="col">
    <?php echo CHtml::dropDownList('team','',(array)$team_list,array(
     'class'=>"lightblue-fields rounded3"
    ))?>
    </div> -->
    
    
    <!-- <div class="col">
    <?php 
    $map_provider = getOptionA('map_provider');
    if($map_provider=="google"){
    echo CHtml::textField('search_map','',array(
      'placeholder'=>Driver::t("Search map"),
      'class'=>"blue-fields rounded3 search_map"
    ));
    } else {
    	echo '<div class="search_map" id="search_map_mapbox"></div>';
    }
    ?>
    </div> -->
    
    </div> <!--search-team-wrap-->
    
    <div class="back-dashboard">
     <a href="<?php echo Yii::app()->createUrl('/app/index')?>">
     <i class="ion-ios-arrow-thin-left"></i> <?php echo Driver::t("Back To Dashboard")?>
     </a>
    </div>
    
    
   
  </div> <!--row-->
  
  <div class="col-sm-3 border top-header-logo"  >    
    <a href="<?php echo Yii::app()->createUrl('/app/index')?>" class="logo">
     <img src="<?php echo FrontFunctions::getLogoURL() ?>">
    </a>
  </div>
  
   <div class="col-sm-5 border text-right top-header-nav" >
       
    <div class="task-remaining-wrap rounded3">
       <div class="task-number">
          <p class="task-number-remaining">0</p>
       </div>
       <div class="task-text"><?php echo t("Task Remaining")?></div>
       <div class="clear"></div>
    </div>
    
    <a href="javascript:;" class="green-button left rounded add-new-task">
    <?php echo t("Add New Task")?>
    </a>
    
    <!--<a href="<?php echo Yii::app()->createUrl('/app/agentnew')?>" class="black-button left rounded">
    <?php echo t("Add New Agent")?>
    </a>-->
    
    <div class="left">
    <ul class="menu">
    
      <li class="mobile-nav-wrap">
        <a href="javascript:;" class="mobile-nav-menu"><i class="ion-android-menu"></i></a>
      </li>
     
      <li class="desktop-nav-wrap">
        <!--<a href="javascript:;" class="menu-pop"><i class="ion-grid"></i></a>-->
        <a href="<?php echo Yii::app()->createUrl('app/settings')?>" class="menu-popx"><i class="ion-grid"></i></a>
        
        <div class="popup_menu nav">
          <div class="row">
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/index')?>">
                  <i class="ion-grid"></i>
                  <p><?php echo Driver::t("Dashboard")?></p>
                </a>
            </div> <!--col-->
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/tasks')?>">
                  <i class="ion-ios-checkmark"></i>
                  <p><?php echo Driver::t("Tasks")?></p>
                </a>
            </div> <!--col-->            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/teams')?>">
                  <i class="ion-android-contacts"></i>
                  <p><?php echo Driver::t("Teams")?></p>
                </a>
            </div> <!--col-->            
                                    
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/agents')?>">
                  <i class="ion-android-contact"></i>
                  <p><?php echo Driver::t("Agents")?></p>
                </a>
            </div> <!--col-->            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/contacts')?>">
                  <i class="ion-android-contacts"></i>
                  <p><?php echo Driver::t("Contacts")?></p>
                </a>
            </div> <!--col-->            
            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/settings')?>">
                  <i class="ion-gear-b"></i>
                  <p><?php echo Driver::t("Settings")?></p>
                </a>
            </div> <!--col-->            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/assignment')?>">
                  <i class="ion-android-car"></i>
                  <p><?php echo Driver::t("Assignment")?></p>
                </a>
            </div> <!--col-->                
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/reports')?>">
                  <i class="ion-ios-paper"></i>
                  <p><?php echo Driver::t("Reports")?></p>
                </a>
            </div> <!--col-->    
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/pushlogs')?>">
                  <i class="ion-chatbox-working"></i>
                  <p><?php echo Driver::t("Push")?></p>
                </a>
            </div> <!--col-->    
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/notifications')?>">
                  <i class="ion-ios-bell"></i>
                  <p><?php echo Driver::t("Notifications")?></p>
                </a>
            </div> <!--col-->    
            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/uploadmasstask')?>">
                  <i class="ion-ios-paper-outline"></i>
                  <p><?php echo Driver::t("Upload Tasks")?></p>
                </a>
            </div> <!--col-->            
            
            <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/smslogs')?>">
                  <i class="ion-android-textsms"></i>
                  <p><?php echo Driver::t("SMS Logs")?></p>
                </a>
            </div> <!--col-->            
            
             <div class="col-xs-6 ">
                <a href="<?php echo Yii::app()->createUrl('/app/teams')?>">
                  <i class="ion-more"></i>
                  <p><?php echo Driver::t("More")?>...</p>
                </a>
            </div> <!--col-->        
            
            
<?php 
$language_list=getOptionA('language_list');
if(!empty($language_list)){
   $language_list=json_decode($language_list,true);	
}   
$action_name=Yii::app()->controller->action->id;
?>

<?php if(is_array($language_list) && count($language_list)>=1):?> 
            <div class="col-xs-6 relative">
                <a href="javascript:;" class="show-lang-list">
                  <i class="ion-ios-flag"></i>
                  <p><?php echo strtoupper(Yii::app()->language)?></p>
                </a>
                <div class="lang-wrapper rounded2">
                 
                <?php if(is_array($language_list) && count($language_list)>=1):?>
                
                <ul id="lang-list">
                 <?php foreach ($language_list as $val_lang) :?>
	             <li>
	               <a href="<?php echo Yii::app()->getBaseUrl(true)."/app/setlang/?lang=$val_lang&action=$action_name"?>">
	                 <?php echo $val_lang?>
	               </a>
	              </li>	           
	             <?php endforeach;?>
	           </ul>
	           
                <?php endif;?>
                 
                </div>
            </div> <!--col-->   
<?php endif;?>
            
            
          </div><!-- row-->
        </div> <!--popup_menu-->
        
      </li>
      <li>
        <a href="javascript:;" class="menu-sound"><i class="ion-volume-high"></i></a>
      </li>
      <li>
         <a href="javascript:;" class="menu-notification"><i class="ion-ios-bell-outline"></i></a>
         
         <div class="popup_menu notification">
           <ul id="notification_list">
           </ul>
         </div>
         
      </li>     
      
      <li>
        <a href="<?php echo Yii::app()->createUrl('app/profile')?>" 
        title="<?php echo Driver::t("Profile")?>" ><i class="ion-android-contact"></i></a>
      </li>
      
      <li>
        <a href="<?php echo Yii::app()->createUrl('app/logout')?>" 
        title="<?php echo Driver::t("logout")?>" ><i class="ion-log-out"></i></a>
      </li>
       
    </ul>
    </div>
   
  </div> <!--row-->
</div> <!--row-->
</div>

protected/views/tpl/menu.php
<?php
$visible=true;

$menu =  array(  		    		    
    'activeCssClass'=>'active', 
    'encodeLabel'=>false,
    'items'=>array(
    
        array('visible'=>true,'label'=>'<i class="ion-grid"></i>&nbsp; '.t('Dashboard'),
        'url'=>array('/app/index'),'linkOptions'=>array()),               
        
        array('visible'=>$visible,'label'=>'<i class="ion-gear-b"></i>&nbsp; '.t("Settings"),
        'url'=>array('/app/settings'),'linkOptions'=>array()),               
        
        array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Collaborators"),
        'url'=>array(),'linkOptions'=>array(), 'items'=>array(

        array('visible'=>true,'label'=>'<i class="ion-android-contacts"></i>&nbsp; '.t("Teams"),
        'url'=>array('/app/teams'),'linkOptions'=>array()),       
        
        array('visible'=>true,'label'=>'<i class="ion-android-contact"></i>&nbsp; '.t("Agents"),
        'url'=>array('/app/agents'),'linkOptions'=>array()),       
        )),
        
        array('visible'=>true,'label'=>'<i class="ion-android-locate"></i>&nbsp; '.t("Agents Track Back"),
        'url'=>array('/app/trackback'),'linkOptions'=>array()),        
        
        array('visible'=>true,'label'=>'<i class="ion-android-contacts"></i>&nbsp; '.t("Contacts"),
        'url'=>array('/app/contacts'),'linkOptions'=>array()),       
        
        array('visible'=>true,'label'=>'<i class="ion-ios-checkmark"></i>&nbsp; '.t("Tasks"),
        'url'=>array('/app/tasks'),'linkOptions'=>array()),       
        
        array('visible'=>true,'label'=>'<i class="ion-ios-paper-outline"></i>&nbsp; '.t("Upload Tasks"),
        'url'=>array('/app/uploadmasstask'),'linkOptions'=>array()),       
        
        array('visible'=>true,'label'=>'<i class="ion-ios-list-outline"></i>&nbsp; '.t("Services"),
        'url'=>array('/app/services'),'linkOptions'=>array()),    
        /*array('visible'=>$visible,'label'=>'<i class="ion-flag"></i>&nbsp; '.t("Language"),
        'url'=>array('/app/language'),'linkOptions'=>array()),        */
                        
        array('visible'=>$visible,'label'=>'<i class="ion-ios-bell"></i>&nbsp; '.t("Notifications"),
        'url'=>array('/app/notifications'),'linkOptions'=>array()),        
                
        array('visible'=>true,'label'=>'<i class="ion-android-car"></i>&nbsp; '.t("Assignment"),
        'url'=>array('/app/assignment'),'linkOptions'=>array()),                
                
        array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Send Bulk Push"),
        'url'=>array('/app/bulkpush'),'linkOptions'=>array()),        


        // array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Modulo Venta"),
        // 'url'=>array(),'linkOptions'=>array(), 'items'=>array(

        //     array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Categories"),
        //     'url'=>array('/app/categories'),'linkOptions'=>array()),        
            
                            
          
        // )),     
        
        array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Push Broadcast Logs"),
        'url'=>array('/app/bulklogs'),'linkOptions'=>array()),        
        
        array('visible'=>$visible,'label'=>'<i class="ion-android-list"></i>&nbsp; '.t("Push Logs"),
        'url'=>array('/app/pushlogs'),'linkOptions'=>array()),                        
        
        array('visible'=>$visible,'label'=>'<i class="ion-android-textsms"></i>&nbsp; '.t("SMS Logs"),
        'url'=>array('/app/smslogs'),'linkOptions'=>array()),        
        
        array('visible'=>$visible,'label'=>'<i class="ion-email"></i>&nbsp; '.t("Email Logs"),
        'url'=>array('/app/emaillogs'),'linkOptions'=>array()),              
                       
        array('visible'=>true,'label'=>'<i class="ion-ios-list"></i>&nbsp; '.t("Reports"),
        'url'=>array('/app/reports'),'linkOptions'=>array()),       
        
     )   
);       
?>

<div class="left-menu">
  <?php $this->widget('zii.widgets.CMenu', $menu);?>
</div> <!--left-menu-->

protected/views/tpl/task_pane2.php
<?php 
$team_list=Driver::teamList( Driver::getUserId());
if($team_list){
	 $team_list=Driver::toList($team_list,'team_id','team_name',
	   Driver::t("All Team")
	 );
}
?>

<div class="blue_panel">
   <div class="row">
     <div class="col-xs-6"><?php echo t("Agent")?></div>
     <div class="col-xs-6 text-right">
     
     <a href="javascript:;" class="filter_map" data-toggle="modal" data-target="#modalMapFilter" >
        <i class="ion-ios-settings"></i>
     </a>
     
     <a href="javascript:setMapCenter();"><i class="ion-ios-navigate-outline"></i></a>
     
     <a href="javascript:loadAgentDashboard();"><i class="ion-android-refresh"></i></a>
     <!--<a href="javascript:;"><i class="ion-ios-search"></i></a>-->
     
     </div><!-- col-->
     <div class="col-xs-6">
         <?php echo CHtml::dropDownList('team','',(array)$team_list,array(
         'class'=>"lightblue-fields rounded3"
         ))?>
     </div>
   </div> <!--row-->   
</div> <!--blue_panel-->


<ul id="tabs">
 <li class="active"><span class="agent-active-total" >0</span> <?php echo t("Active")?></li>
 <li><span class="agent-offline-total" >0</span> <?php echo t("Offline")?></li>
 <li><span class="agent-total-total">0</span> <?php echo t("Total")?></li>
</ul>

<ul id="tab" class="list_row">
 <li class="active agent-active">

 </li>
 <li class="agent-offline">

 </li>
 
 <li class="agent-total">

 </li>
</ul>

<?php 
$this->renderPartial('/app/filter_map',array(   
));
?>

protected/views/tpl/task_panel.php
<div class="blue_panel">
    
  <?php echo t("Tasks")?>
  
  <?php
  $date_now=date('Y-m-d');    
  $date_now_pretty=date("d M Y");
  echo CHtml::textField('calendar',$date_now_pretty,array(
    'class'=>"lightblue-fields rounded3 medium center"
  ));
  
  echo CHtml::hiddenField('calendar_formated',$date_now,array(
    'class'=>'calendar_formated'
  ))
  ?>

    <!-- <div> -->
    
    <!-- <?php 
    echo CHtml::textField('search-text','',array(
      'placeholder'=>Driver::t("Search map"),
      'class'=>"lightblue-fields rounded3 medium center"
    ));
    ?> -->
    <!-- </div> -->
</div>

<ul id="tabs"> 
 <li class="active"><span class="task-total-unassigned">0</span> <?php echo t("Unassigned")?></li>
 <li><span class="task-total-assigned">0</span> <?php echo t("Assigned")?></li>
 <li><span class="task-total-completed">0</span> <?php echo t("Completed")?></li>
</ul>

<ul id="tab" class="list_row">
 <li class="active task_unassigned">    
 
 </li>
 <li class="task_assigned">
     
 </li>
 <li class="task_completed">
     
 </li>
</ul>

protected/views/tpl/teams.php
<div id="layout_1">
<?php 
$this->renderPartial('/tpl/layout1_top',array(   
));
?> 
</div> <!--layout_1-->

<div class="parent-wrapper">

 <div class="content_1 black">   
   <?php 
   $this->renderPartial('/tpl/menu',array(   
   ));
   ?>
 </div> <!--content_1-->
 
 <div class="content_main">

   <div class="nav_option">
      <div class="row">
        <div class="col-md-6 border">
         <b><?php echo t("Teams")?></b>
        </div> <!--col-->
        <div class="col-md-6 border text-right">
            
           <a class="green-button left rounded" href="javascript:;"
           data-toggle="modal" data-target=".create-team" >
           <?php echo t("Create Team")?>
           </a>           
           
           <a class="orange-button left rounded refresh-table" href="javascript:;">
           <?php echo t("Refresh")?>
           </a>
           
           <a class="green-button left rounded" href="<?php echo Yii::app()->createUrl('/app/bulkpush')?>">
           <?php echo t("Send Bulk Push")?>
           </a>           
           
        </div> <!--col-->
      </div> <!--row-->
   </div> <!--nav_option-->
  
   <div class="inner">
   <form id="frm_table" class="frm_table">
   <?php echo CHtml::hiddenField('action','TeamList')?>
   <table id="table_list" class="table table-hover">
   <thead>
    <tr>
      <th width="5%"><?php echo t("ID")?></th>
      <th width="15%" ><?php echo t("Team Name")?></th>
      <th width="10%"><?php echo t("Total Driver")?></th>
      <th width="10%"><?php echo t("Status")?></th>
      <th width="10%"><?php echo t("Date")?></th>
    </tr>
    </thead>
    <tbody>   
    </tbody>    
   </table>
   </form>
   </div>
 
 </div> <!--content_2-->

</div> <!--parent-wrapper-->


<?php 
$this->renderPartial('/app/team-new',array(   
));